'\" t
.\"     Title: take
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/19/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TAKE" "1" "12/19/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
take \- List Selection Utility
.SH "SYNOPSIS"
.sp
\fBtake\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
Purpose of take(1) is to provide a convenient way for selecting items from a list within a text terminal interactively\&. \fBtake\fR is the best tool for filtering a selection when the list of items can\(cqt be matched with wildcards or regexps, i\&.e\&. they don\(cqt share substrings\&.
.SH "INTRODUCTION"
.sp
\fBtake\fR is a tool used for selecting items from a list interactively and executing a command with the selection\&.
.sp
The list is generated by executing input\-command or reading from STDIN\&. After selection from the list is done, the output\-command is performed on the selection\&. If no output\-command is defined, the selected items are output to STDOUT\&.
.sp
Example invocation for deleting files:
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> ls | take \-c "rm @"
.fi
.if n \{\
.RE
.\}
.sp
Here the list is produced by \fIls\fR command\&. \fBtake\fR is used to filter the input list in order to define the files that should be removed\&. The command option (\fI\-c\fR) is used by replacing "@" with each selected item(s)\&. For example if a file called "foo\&.txt" was selected, then "rm foo\&.txt" would be executed\&.
.SH "LIST SELECTION"
.sp
After \fBtake\fR has the input list ready, the user uses one\-key selection commands to make the selection from list view on the terminal window\&.
.sp
Example list view:
.sp
.if n \{\
.RS 4
.\}
.nf
  * Item1
  * Item2
    Item3
.fi
.if n \{\
.RE
.\}
.sp
In the example list items "Item1" and "Item2" are selected and item "Item3" is not selected\&.
.sp
The selection is performed using the following one\-key commands:
.sp
.if n \{\
.RS 4
.\}
.nf
"J": Toggle selection and move down
"K": Toggle selection and move up
"j": Move down
"k": Move up
"n": Move down page
"p": Move up page
"b": Move to beginning of list
"e": Move to end of list
"g": Goto to <line> (or relative with +/\- <line>)
"s": Select current
"r": Reject current
"t": Toggle current
"S": Select all items
"R": Reject all items
"T": Toggle all items
"c": Toggle the next <count> items (or set/reset with +/\- <count>)
"m": Select items matching the prompted regexp (case insensitive)
"M": Select items matching the prompted regexp (case sensitive)
"f": Find mode with case insensitive matching (Keys: j,k,s,r,t,RET,ESC)
"F": Find mode with case sensitive matching (Keys: j,k,s,r,t,RET,ESC)
"v": View the list of commands that would be executed
"i": View the current list entry content (if a text file)
"l": Center list view on screen around current line
"h": Show command help
"x": Quit and execute output\-command for selection
"q": Quit and skip output\-command execution
.fi
.if n \{\
.RE
.\}
.sp
Typically the user presses "j" with or without SHIFT, i\&.e\&. moves down and skips/selects lines\&. Moving up/down can be performed also page by page with "p" and "n"\&. "S", "R", "T" are used for affecting all the lines\&.
.sp
"g" is used for jumping to an absolute line or for jumping relatively from current line\&. The jump value is prompted from the user\&. A plain number means absolute line number\&. "+" before the number means moving down the number of lines, and "\-" means moving up the number of lines\&.
.sp
"c" can be used to select multiple lines\&. The "count" is given to prompt and has optional set/unset specifier\&. If value starts with "+" then items are set and if with "\-" items are unset\&. If the prompted value is a plain number, then "count" items are toggled\&.
.sp
"m" and "f" can be used to select items based on regexp pattern\&. "m" operates non\-interactively by selecting all matching lines and "f" operates interactively\&.
.sp
If files are to be removed with \fBtake\fR, it is sensible to check the list of commands before they are actually executed\&. "v" command can be used for this\&.
.sp
Press "h" for online command help display\&.
.SH "OUTPUT COMMAND FORMATTING"
.sp
The output\-command syntax has a special tag ("@") for transferring the selection into the output\-command(s)\&. "@" is replaced with the selected item before output\-command is executed\&. "@" may appear multiple times in the command\&. "@_" means literal "@" in the output, i\&.e\&. if the user needs the "@" character in the output and not an item from the list selection\&.
.sp
By default the output\-command is executed once per selected line\&. The \fI\-j\fR switch can be used to join selection with <join> string\&. <join> string is " " by default\&. If selection is joined, the output\-command is executed only once and "@" is replaced with the joined selection\&.
.sp
See:
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> take \-h
.fi
.if n \{\
.RE
.\}
.sp
for a complete list of command line options\&.
.SH "EXAMPLE EXECUTIONS"
.sp
First, a safe trial:
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> take \-a \*(Aqecho @\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Other Examples:
.sp
Example1: Pipe directory listing to \fBtake\fR for file removal\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> ls | take \-c \*(Aqrm \-f @\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Example2: Same as "Example1" but with selection joined\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> ls | take \-j \-c \*(Aqrm \-f @\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Example3: Same as "Example1" but without shell piping\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> take \-a \*(Aqrm \-f @\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Example4: Echo input list selection with items surrounded by \fI@@\fR strings\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> take \-a \*(Aqecho @_@_@@_@_\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Example5: Select a list of files/dirs to be removed hierarchically\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  shell> take \-i "find \&." \-c "rm \-rf \e"@\e""
.fi
.if n \{\
.RE
.\}
.SH "SHELL ALIASES/FUNCTIONS"
.sp
These aliases (or functions) would be useful for shell users\&.
.sp
Function1: Select files to remove from current directory\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  alias lcrm=\*(Aqtake \-a "rm \-rf \e"@\e""\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Function2: Select files to remove from current directory hierarchically\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  alias lcrrm=\*(Aqtake \-i \e"find \&.\e" \-c "rm \-rf \e"@\e""\*(Aq
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\fB\-i, \-\-input\fR=\fIINPUT\fR
.RS 4
\fIINPUT\fR
is a shell command that is used to create list for
\fBtake\fR\&.
.RE
.PP
\fB\-l, \-\-list\fR=\fIDIR\fR
.RS 4
\fBtake\fR
creates the list from given directory or from current directory entries when no argument given to option\&. "\&." and "\&.\&." entries are neglegted\&.
.RE
.PP
\fB\-c, \-\-command\fR=\fICOMMAND\fR
.RS 4
Option specifies the
\fICOMMAND\fR
that is executed for each selected item\&. If
\fB\-\-join\fR
option is given then the command is executed only once\&.
.RE
.PP
\fB\-a, \-\-auto\fR=\fIAUTO\fR
.RS 4
This is a convenience option that is same as giving
\fB\-\-list\fR
and
\fB\-\-command\fR
options together\&. Option parameter is used the same way as with
\fB\-\-command\fR\&.
.RE
.PP
\fB\-j, \-\-join\fR=\fIJOIN\fR
.RS 4
Join the selection using
\fIJOIN\fR
as joining string\&. If option parameter is not given, the joining string is SPACE (" ")\&.
.RE
.PP
\fB\-p, \-\-presel\fR
.RS 4
Selection list is preselected, i\&.e\&. each item in the list is marked selected\&. By default all items are non\-selected\&.
.RE
.PP
\fB\-pl, \-\-presel_list\fR
.RS 4
Numbered list items are preselected\&. If
\fB\-\-presel\fR
is given, then the numbered lines are actually inverted\&.
.RE
.PP
\fB\-pf, \-\-presel_file\fR=\fIFILE\fR
.RS 4
Line numbers are taken from
\fIFILE\fR\&. The numbers are used to make preselection\&. If
\fB\-\-presel\fR
is given, then the numbered lines are actually inverted\&.
.RE
.PP
\fB\-b, \-\-batch\fR
.RS 4
Run
\fBtake\fR
in batch mode\&. Interaction is skipped\&. In practice some form of pre\-selection has to be performed, otherwise output is empty\&.
.RE
.PP
\fB\-s, \-\-selected\fR
.RS 4
Display selected line numbers to stdout\&. Output can be saved to for example
\fB\-\-presel_file\fR
and later used in a script\&.
.RE
.PP
\fB\-x, \-\-no_exec\fR
.RS 4
Command given with
\fB\-\-command\fR
is not executed if this option is given\&. Instread the commands are stored to a file\&. Option parameter defines the name of the output file\&. If omitted, STDOUT is used\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error)
.RE
.SH "AUTHOR"
.sp
\fBtake\fR was originally written by Tero Isannainen\&.
.SH "COPYING"
.sp
Copyright (C) 2015 Tero Isannainen\&.
